version: '3'
services:
  db:
    build: .
    container_name: db_gestion
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
      - '3307:3307'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql#