version: '3'
services:
  db:
    build: .
    container_name: db_expo
    restart: always
    environment:
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
      - '3307:3307'